dynamics_webform_lookup.settings:
  type: config_object
  label: 'Dynamics Webform Lookup Settings'
  mapping:
    api_secret_id:
      type: string
      label: 'Dynamics API Secret ID'
    api_key_id:
      type: string
      label: 'Dynamics API Key ID'
    environment:
      type: string
      label: 'Active Environment'
    api_url_dev:
      type: string
      label: 'Dev API URL'
    api_url_prod:
      type: string
      label: 'Prod API URL'